### ISSUE TITLE
OG app for SEO tags

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#4342]
```[tasklist]
### Tasks
- [ ] https://github.com/heyxyz/hey/issues/4343
- [ ] https://github.com/heyxyz/hey/issues/4344
- [ ] https://github.com/heyxyz/hey/issues/4345
- [ ] https://github.com/heyxyz/hey/issues/4369
- [ ] https://github.com/heyxyz/hey/issues/4370
```
