### ISSUE TITLE
Add test coverage to all API endpoints

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#4385]
```[tasklist]
### Tasks
- [ ] https://github.com/heyxyz/hey/issues/4387
- [ ] https://github.com/heyxyz/hey/issues/4388
- [ ] https://github.com/heyxyz/hey/issues/4389
- [ ] https://github.com/heyxyz/hey/issues/4390
- [ ] https://github.com/heyxyz/hey/issues/4391
- [ ] https://github.com/heyxyz/hey/issues/4392
- [ ] https://github.com/heyxyz/hey/issues/4393
- [ ] https://github.com/heyxyz/hey/issues/4394
- [ ] https://github.com/heyxyz/hey/issues/4395
- [ ] https://github.com/heyxyz/hey/issues/4396
- [ ] https://github.com/heyxyz/hey/issues/4397
- [ ] https://github.com/heyxyz/hey/issues/4398
- [ ] https://github.com/heyxyz/hey/issues/4399
- [ ] https://github.com/heyxyz/hey/issues/4400
- [ ] https://github.com/heyxyz/hey/issues/4401
- [ ] https://github.com/heyxyz/hey/issues/4402
- [ ] https://github.com/heyxyz/hey/issues/4403
- [ ] https://github.com/heyxyz/hey/issues/4404
- [ ] https://github.com/heyxyz/hey/issues/4405
- [ ] https://github.com/heyxyz/hey/issues/4406
- [ ] https://github.com/heyxyz/hey/issues/4407
- [ ] https://github.com/heyxyz/hey/issues/4408
- [ ] https://github.com/heyxyz/hey/issues/4409
- [ ] https://github.com/heyxyz/hey/issues/4410
- [ ] https://github.com/heyxyz/hey/issues/4411
- [ ] https://github.com/heyxyz/hey/issues/4412
- [ ] https://github.com/heyxyz/hey/issues/4413
- [ ] https://github.com/heyxyz/hey/issues/4414
- [ ] https://github.com/heyxyz/hey/issues/4415
- [ ] https://github.com/heyxyz/hey/issues/4416
- [ ] https://github.com/heyxyz/hey/issues/4417
- [ ] https://github.com/heyxyz/hey/issues/4418
- [ ] https://github.com/heyxyz/hey/issues/4419
- [ ] https://github.com/heyxyz/hey/issues/4420
- [ ] https://github.com/heyxyz/hey/issues/4421
- [ ] https://github.com/heyxyz/hey/issues/4422
- [ ] https://github.com/heyxyz/hey/issues/4423
- [ ] https://github.com/heyxyz/hey/issues/4424
- [ ] https://github.com/heyxyz/hey/issues/4425
- [ ] https://github.com/heyxyz/hey/issues/4426
- [ ] https://github.com/heyxyz/hey/issues/4427
- [ ] https://github.com/heyxyz/hey/issues/4428
- [ ] https://github.com/heyxyz/hey/issues/4429
- [ ] https://github.com/heyxyz/hey/issues/4430
- [ ] https://github.com/heyxyz/hey/issues/4431
- [ ] https://github.com/heyxyz/hey/issues/4432
- [ ] https://github.com/heyxyz/hey/issues/4433
- [ ] https://github.com/heyxyz/hey/issues/4434
- [ ] https://github.com/heyxyz/hey/issues/4435
- [ ] https://github.com/heyxyz/hey/issues/4436
```
