### ISSUE TITLE
Migrate to Family Connectkit

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#4464]
```[tasklist]
### Tasks
- [x] Add custom themes
- [x] Test on desktop
- [x] Test on mobile
- [x] Test with metamask for switch network
- [x] Revisit modal open usage
- [x] Check and fix WalletSelector usage
- [x] Test no profile collects
```
